version: 0.2

phases:
  install:
    runtime-versions:
      node: 12

  pre_build:
    # Installs and exports some varibles from the .fargate config file
    commands:
      - npm i -g envgate
      - export TAG=$CODEBUILD_BUILD_NUMBER
      - export CONFIG=.fargate/config.json
      - export STAGE_CONFIG=.fargate/env.$STAGE.json
      - export IMAGE_NAME=$(envgate -f $STAGE_CONFIG -t $CONFIG --get IMAGE_NAME)
      - export ECR_URL=$(envgate -f $STAGE_CONFIG -t $CONFIG --get ECR_URL)
      - export CLUSTER_NAME=$(envgate -f $STAGE_CONFIG -t $CONFIG --get CLUSTER_NAME)
      - export SERVICE_NAME=$(envgate -f $STAGE_CONFIG -t $CONFIG --get SERVICE_NAME)
      - export FAMILY_NAME=$(envgate -f $STAGE_CONFIG -t $CONFIG --get FAMILY_NAME)

  build:
    commands:
      # Build you application here
      - echo $IMAGE_NAME
      - docker build -t $IMAGE_NAME .

  post_build:
    commands:
      - echo "building new taskdef with envgate...."
      - envgate -f .fargate/env.$STAGE.json -f .fargate/config.json -o task-definition.out.json -t .fargate/task-definition.json
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo $ECR_URL
      - docker tag $IMAGE_NAME $ECR_URL
      - docker push $ECR_URL
      - cat task-definition.out.json
      - TASK_VERSION=$(aws ecs register-task-definition --family $FAMILY_NAME --cli-input-json file://task-definition.out.json | jq --raw-output '.taskDefinition.revision')
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $FAMILY_NAME:$TASK_VERSION
